### ISSUE TITLE
Get current logged in user object

### ISSUE THREAD

**Issue by heisler98** [colingoodman/flaskchat#20]
Akin to `/whoami`, I could use a `/users/me` (or equivalent) that returned the logged-in user's object. Alternatively, any way that the API could distinguish the current user from B-list users would be preferable. Perhaps `/users/list` could return the currently logged in user first?

**Comment by colingoodman** [comment]
Latest commit now has `/users/me` that returns the authenticated user's information. `/users/list` will also now always feature the authenticated user first in the list.
