### ISSUE TITLE
cors_allowed_origins necessary in socketio app call

### ISSUE THREAD

**Issue by heisler98** [colingoodman/flaskchat#3]
I think I made a PR about this moons ago in master, but FYI – 
socketio requires `socketio = SocketIO(app, cors_allowed_origins='publicly-accessible-address')`
For testing purposes, we can do `socketio = SocketIO(app, cors_allowed_origins='*')`

Without this, WS doesn't work (at least for me). I forget the fixes, and I'm concerned if we don't catalog them we have to go on the hunt again.

**Comment by colingoodman** [comment]
A fix including `cors_allowed_origins='*'` as requested has been pushed to master.
