### ISSUE TITLE
DecodeError - Not enough segments

### ISSUE THREAD

**Issue by colingoodman** [colingoodman/flaskchat#39]
When connecting via the web app, the following exception occurs:

> Jul 12 10:52:33 macpro python3.9[1357738]: message handler error
Jul 12 10:52:33 macpro python3.9[1357738]: Traceback (most recent call last):
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/jwt/api_jws.py", line 187, in _load
Jul 12 10:52:33 macpro python3.9[1357738]:     signing_input, crypto_segment = jwt.rsplit(b".", 1)
Jul 12 10:52:33 macpro python3.9[1357738]: ValueError: not enough values to unpack (expected 2, got 1)
Jul 12 10:52:33 macpro python3.9[1357738]: The above exception was the direct cause of the following exception:
Jul 12 10:52:33 macpro python3.9[1357738]: Traceback (most recent call last):
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/engineio/server.py", line 603, in _trigger_event
Jul 12 10:52:33 macpro python3.9[1357738]:     return self.handlers[event](*args)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/socketio/server.py", line 742, in _handle_eio_message
Jul 12 10:52:33 macpro python3.9[1357738]:     self._handle_connect(eio_sid, pkt.namespace, pkt.data)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/socketio/server.py", line 638, in _handle_connect
Jul 12 10:52:33 macpro python3.9[1357738]:     success = self._trigger_event(
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/socketio/server.py", line 714, in _trigger_event
Jul 12 10:52:33 macpro python3.9[1357738]:     return self.handlers[namespace][event](*args)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 284, in _handler
Jul 12 10:52:33 macpro python3.9[1357738]:     return self._handle_event(handler, message, namespace, sid,
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 763, in _handle_event
Jul 12 10:52:33 macpro python3.9[1357738]:     ret = handler(auth)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
Jul 12 10:52:33 macpro python3.9[1357738]:     verify_jwt_in_request(optional, fresh, refresh, locations)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
Jul 12 10:52:33 macpro python3.9[1357738]:     jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request
Jul 12 10:52:33 macpro python3.9[1357738]:     decoded_token = decode_token(encoded_token, csrf_token)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/utils.py", line 122, in decode_token
Jul 12 10:52:33 macpro python3.9[1357738]:     return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/jwt_manager.py", line 515, in _decode_jwt_from_config
Jul 12 10:52:33 macpro python3.9[1357738]:     unverified_claims = jwt.decode(
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
Jul 12 10:52:33 macpro python3.9[1357738]:     decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/jwt/api_jwt.py", line 90, in decode_complete
Jul 12 10:52:33 macpro python3.9[1357738]:     decoded = api_jws.decode_complete(
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/jwt/api_jws.py", line 146, in decode_complete
Jul 12 10:52:33 macpro python3.9[1357738]:     payload, signing_input, header, signature = self._load(jwt)
Jul 12 10:52:33 macpro python3.9[1357738]:   File "/tiny/flask_venv/lib/python3.9/site-packages/jwt/api_jws.py", line 190, in _load
Jul 12 10:52:33 macpro python3.9[1357738]:     raise DecodeError("Not enough segments") from err

So far, no impact on functionality has been found.

**Comment by johnchapple** [comment]
I think I fixed this now that I am sending them to login themselves after signing up.
