### ISSUE TITLE
Events sent to old socket after disconnection

### ISSUE THREAD

**Issue by heisler98** [colingoodman/flaskchat#41]
This is a reproducible issue via the following steps:

1) Connect to WS.
2) Close client connection.
3) Reopen client connection (usually within 1 minute). 
4) Emit a message to server.

Result: 
Server will emit the message to the socket which was closed in step 2. It will not emit a message to the socket opened in step 3. 

Expected result: 
Server will emit message to the socket opened in step 3. 

Here is a log example: 
```Jul 12 23:18:07 macpro python3.9[1376966]: [2021-07-12 23:18:07,509] INFO in sockets: A socket with ID 6rO2bAONabr7tDYUAADv disconnected...
Jul 12 23:18:07 macpro python3.9[1376966]: [2021-07-12 23:18:07,509] INFO in sockets: 6rO2bAONabr7tDYUAADv belonged to hunter. They now have the following sockets open: ['WPArMinhM3QBu_GKAADx']
Jul 12 23:18:07 macpro python3.9[1376966]: [2021-07-12 23:18:07,509] INFO in sockets: {'colingoodman': [], 'crabman': [], 'testone': [], 'hunter': ['WPArMinhM3QBu_GKAADx']}
Jul 12 23:18:07 macpro python3.9[1376966]: [2021-07-12 23:18:07,509] INFO in sockets: Sent to 6rO2bAONabr7tDYUAADv```

**Comment by colingoodman** [comment]
I wonder if socketio is "recovering" your socket when you reconnect on the assumption that it may have been dropped from bad internet or whatever. If so, this may simply be an option I could turn off. I will look into it.

**Comment by heisler98** [comment]
This "old socket persistence" issue happens even after the course of several minutes. I cannot exactly reproduce this issue yet.

**Comment by colingoodman** [comment]
This should be fixed having restored the WS.
