### ISSUE TITLE
Socket timestamp differs from API timestamp

### ISSUE THREAD

**Issue by heisler98** [colingoodman/flaskchat#44]
This is anal, but would save me some date formatting checks. 

Result: 
- Socket timestamp - `2021-07-13 19:16:31.131044`
- API timestamp - `Mon, 12 Jul 2021 16:48:21 GMT`

Expected result: 
One timestamp format standard from server.

**Comment by colingoodman** [comment]
This is likely because mongo stores the time differently from whatever python is doing by default. I can look into some consistency.

**Comment by colingoodman** [comment]
I went ahead and changed _both_ to use time in seconds since the epoch started or whatever that standard is.
